/* cspell:disable-file */
import {
  LayoutDashboard, CheckSquare, FlaskConical, FileText, GitBranch,
  Rocket, Globe, Compass, Code, ServerCog, Database, BarChart3,
  Activity, ClipboardCheck, BookOpen, Folder, Settings, Cpu,
  Keyboard, Zap, ListChecks, type LucideIcon,
} from "lucide-react"

// ── Types ────────────────────────────────────────────────────────────────────

export interface DocSubsection {
  id: string
  title: string
  content: string
  tips?: string[]
}

export interface DocSection {
  id: string
  title: string
  icon: LucideIcon
  description: string
  subsections: DocSubsection[]
}

// ── Documentation Content ────────────────────────────────────────────────────

export const DOC_SECTIONS: DocSection[] = [
  // ─── 1. Dashboard ────────────────────────────────────────────────────────
  {
    id: "dashboard",
    title: "Dashboard",
    icon: LayoutDashboard,
    description: "The Dashboard is your central command hub, providing a real-time overview of project health, test status, collaboration flow, and release readiness at a glance.",
    subsections: [
      {
        id: "dashboard-metrics",
        title: "Execution Snapshot Metrics",
        content: "The top section displays key QA metrics as clickable stat cards:\n\n- **Open Tasks** — count of unresolved tasks with drill-down capability\n- **Critical / Blocker** — tasks at critical or blocker severity, color-coded for urgency\n- **Overdue Tasks** — tasks past their due date\n- **Test Pass Rate** — percentage with breakdown (passed / total)\n- **Failed Tests** — count with alert state highlighting\n- **Not-Run Tests** — backlog of unexecuted test cases\n- **Test Coverage %** — overall coverage with gap analysis",
      },
      {
        id: "dashboard-collab",
        title: "Collaboration Flow Metrics",
        content: "Track the QA-Dev handoff pipeline:\n\n- **Awaiting Dev Acknowledgement** — handoffs waiting for developer response\n- **Ready for QA** — items returned from dev, ready for retest\n- **Verified Today** — items verified in the current session\n- **Missing Evidence** — handoffs lacking required evidence (screenshots, logs)\n- **PRs Waiting QA** — pull requests needing QA review\n- **Avg Dev Acknowledgement** — average hours for dev to acknowledge bugs\n- **Evidence Health** — overall handoff completeness indicators\n- **Verification Reopen Rate %** — percentage of items that failed verification",
      },
      {
        id: "dashboard-charts",
        title: "Charts & Visualizations",
        content: "Interactive charts provide trend analysis:\n\n- **Test Status Donut Chart** — visual breakdown of pass/fail/blocked/not-run\n- **Pass Rate Trend** — line chart showing the last 12 test runs\n- **Sprint Test Burndown** — tracks test completion within the active sprint\n- **Defect Density by SAP Module** — bar chart grouping defects by module\n- **Coverage Gaps / Upcoming Due Dates** — panel highlighting areas needing attention\n- **Test Case Aging** — distribution of stale tests (7+, 30+, 90+ days)\n- **Execution Velocity** — test throughput over the last 30 days",
      },
      {
        id: "dashboard-quality-gates",
        title: "Release Readiness Quality Gates",
        content: "A set of configurable quality criteria that must pass before release:\n\n- **Pass Rate >=** threshold (e.g. 95%)\n- **Critical Bugs <=** threshold (e.g. 0)\n- **Smoke Tests** pass rate\n- **Coverage % >=** threshold\n- **Blockers <=** threshold\n\nEach gate shows a pass/fail indicator. All gates must pass for the release to be considered ready.",
        tips: ["Quality gates are evaluated against the active project's current data. Keep your test executions up to date for accurate readiness assessment."],
      },
      {
        id: "dashboard-standup",
        title: "AI Standup Summary",
        content: "Click the **Generate Standup** button to produce an AI-powered daily standup summary. The summary is generated by Gemini and includes:\n\n- Recent test run results\n- Verified items and their outcomes\n- High-priority open tasks\n- Collaboration state changes\n\nThe standup is formatted for quick copy-paste into Slack or Teams.",
        tips: ["Requires a configured Google AI Studio API key in Settings."],
      },
      {
        id: "dashboard-sprint",
        title: "Sprint Context Filter",
        content: "Use the sprint dropdown at the top of the Dashboard to filter all metrics to a specific sprint or view \"All Issues\". When a sprint is selected, every metric, chart, and summary section recalculates to show only data relevant to that sprint.",
      },
    ],
  },

  // ─── 2. Tasks ────────────────────────────────────────────────────────────
  {
    id: "tasks",
    title: "Tasks",
    icon: CheckSquare,
    description: "The Tasks page is your primary work management hub with a Kanban board, advanced filtering, AI-powered analysis, and deep integrations with Linear and Jira.",
    subsections: [
      {
        id: "tasks-board",
        title: "Task Board & Views",
        content: "Two view modes are available:\n\n- **Kanban Board** — drag-and-drop columns organized by status. Manually reorder tasks within and across columns.\n- **Triage View** — tasks grouped by risk assessment for prioritization.\n\nSwitch between views using the toggle at the top of the page.",
      },
      {
        id: "tasks-sources",
        title: "Task Sources & Sync",
        content: "Tasks can come from multiple sources:\n\n- **Manual** — create tasks directly in QAssistant\n- **Linear** — sync issues from Linear with automatic workflow state mapping\n- **Jira** — sync issues from Jira with status transition support\n\nAuto-sync keeps your tasks up to date with a configurable polling interval. Each synced task retains a link to its external source for quick navigation.",
        tips: ["Configure Linear or Jira connections in Settings before syncing. You can have multiple connections per project."],
      },
      {
        id: "tasks-filters",
        title: "Filtering & Search",
        content: "Powerful filtering options to narrow down your task list:\n\n- **Status** — open, closed, or all\n- **Priority** — low, medium, high, critical\n- **Severity** — cosmetic, minor, major, critical, blocker\n- **Assignee** — filter by team member\n- **Component** — filter by app module\n- **Labels / Tags** — custom tag filtering\n- **Sprint** — filter by sprint assignment\n- **Due Date** — overdue, upcoming, or all\n- **Collaboration State** — draft, ready_for_dev, dev_acknowledged, in_fix, ready_for_qa, qa_retesting, verified, closed\n- **Handoff State** — incomplete or complete\n- **Coverage State** — uncovered or covered\n\nSave frequently used filter combinations as **Filter Presets** for quick recall.",
      },
      {
        id: "tasks-cards",
        title: "Task Cards & Details",
        content: "Each task card displays:\n\n- Title with formatted text support\n- Status badge and priority/severity indicators\n- Assignee avatar and name\n- Due date with overdue highlighting\n- AI Analysis button for quick insights\n- External link to Linear/Jira\n- Copy reference button for sharing\n- Tags and labels\n\nClick a task to open the **Details Sidebar** where you can edit all metadata, view analysis history, trigger AI analysis, generate bug reports (PDF), and manage the collaboration lifecycle.",
      },
      {
        id: "tasks-ai",
        title: "AI Analysis",
        content: "Click the **Analyze** button on any task to get an AI-powered analysis. The Gemini model examines the task description, comments, and context to provide:\n\n- Root cause assessment\n- Impact analysis\n- Suggested reproduction steps\n- Recommended test areas\n- Priority justification\n\nAnalysis results are saved with timestamps and can be reviewed in the Analysis History panel. You can delete individual analysis entries.",
        tips: ["AI analysis works best with detailed task descriptions. Include steps to reproduce, expected vs actual behavior, and environment details."],
      },
      {
        id: "tasks-handoffs",
        title: "Handoff Workflow",
        content: "The handoff system manages the QA-to-Dev communication lifecycle:\n\n1. **Draft** — QA creates a handoff packet with bug details, screenshots, and evidence\n2. **Ready for Dev** — QA marks the handoff as ready for developer review\n3. **Dev Acknowledged** — developer confirms receipt\n4. **In Fix** — developer is working on the fix\n5. **Ready for QA** — developer marks the fix as ready for retest\n6. **QA Retesting** — QA is verifying the fix\n7. **Verified** — fix confirmed working\n8. **Closed** — issue resolved\n\nHandoff packets support structured bug types: UI, API, Data, Performance, and Security. Each type has a tailored template.",
      },
      {
        id: "tasks-collab",
        title: "Collaboration Timeline",
        content: "Every state transition is logged in the Collaboration Timeline, creating an audit trail of who did what and when. Events include handoff creation, acknowledgements, fix submissions, retests, and verifications.\n\nThe timeline is visible in the task detail sidebar and in the Activity Feed page.",
      },
    ],
  },

  // ─── 3. Tests ────────────────────────────────────────────────────────────
  {
    id: "tests",
    title: "Tests",
    icon: FlaskConical,
    description: "Comprehensive test management covering test case creation, execution tracking, reporting, coverage analysis, regression building, risk assessment, and AI accuracy evaluation.",
    subsections: [
      {
        id: "tests-generation",
        title: "Test Case Generation",
        content: "Generate test cases from multiple sources:\n\n- **From Linear/Jira Issues** — select tasks and let AI generate comprehensive test cases with preconditions, steps, test data, and expected results\n- **From Free Text** — paste feature descriptions or requirements for AI to analyze\n- **Design Document Upload** — attach design docs for additional context during generation\n- **Batch CSV Import** — import existing test cases from CSV files\n\nGenerated cases are organized into **Test Plans** with timestamps and source tracking.",
        tips: ["For best AI-generated test cases, provide detailed acceptance criteria and edge cases in your task descriptions."],
      },
      {
        id: "tests-runs",
        title: "Test Runs & Execution",
        content: "Execute tests in structured sessions:\n\n- Create a new test run session with environment selection\n- Execute cases individually, marking each as **passed**, **failed**, **blocked**, or **skipped**\n- Add notes and duration per execution\n- Environment snapshots are captured per execution\n- **Retest Failed** button to quickly re-run all failed cases from a previous run\n\nExecution history is preserved for trend analysis and reporting.",
      },
      {
        id: "tests-reports",
        title: "Reports & Exports",
        content: "Export your test data in multiple formats:\n\n- **Test Summary (Markdown)** — formatted summary with pass rates and plan breakdowns\n- **Test Summary (PDF)** — printable PDF report\n- **Test Cases (CSV)** — all test cases with metadata\n- **Execution History (CSV)** — full execution log\n\nPre-export statistics show total tests, passed, failed, blocked counts, pass rate, per-plan breakdowns, and **Flaky Test** detection (tests that alternate between pass and fail).",
      },
      {
        id: "tests-coverage",
        title: "Coverage Matrix",
        content: "A visual matrix showing which tasks have corresponding test coverage. Each row represents a task and each column indicates whether test cases exist that reference that task's ID.\n\nUncovered tasks are highlighted, making it easy to identify gaps in your test suite.",
      },
      {
        id: "tests-regression",
        title: "Regression Builder",
        content: "Build regression suites from multiple criteria:\n\n- **Date Range** — select completed tasks within a from/to date range\n- **Done-Linked Cases** — test cases linked to completed tasks\n- **Previously Failed** — cases that failed in the most recent execution\n- **AI Smoke Subset** — AI-recommended minimal smoke test selection\n\nThe builder combines selections, deduplicates, and creates a new test plan as your regression suite.",
        tips: ["Use the regression builder before each release to ensure comprehensive coverage of recent changes."],
      },
      {
        id: "tests-risk",
        title: "Risk Matrix",
        content: "Risk scoring prioritizes your test cases based on weighted factors:\n\n- **Module Criticality (30%)** — how critical the module is to the business\n- **Failure Rate (30%)** — historical failure frequency\n- **Defect Count (20%)** — number of associated defects\n- **Task Priority (20%)** — priority of linked tasks\n\nTest cases are color-coded: **High** (red), **Medium** (orange), **Low** (yellow), **Minimal** (green). Each case shows a detailed factor breakdown.",
      },
      {
        id: "tests-ai-accuracy",
        title: "AI Accuracy Evaluation",
        content: "A dedicated module for evaluating AI chatbot response quality:\n\n- **Test Suites** — create evaluation suites with reference documents\n- **Q&A Pairs** — define question-answer pairs (manual or CSV import)\n- **Evaluation Runs** — run evaluations that score responses on 4 dimensions:\n  - Factual Accuracy\n  - Completeness\n  - Faithfulness (to reference docs)\n  - Relevance\n- **Radar Charts** — visualize dimension scores\n- **Run History & Comparison** — track scores over time and compare runs side-by-side",
      },
      {
        id: "tests-ai-suggestions",
        title: "AI Test Suggestions",
        content: "The AI provides two types of test guidance:\n\n- **Criticality Assessment** — analyzes your test suite and identifies which tests matter most based on risk, coverage gaps, and recent changes\n- **Test Run Suggestions** — recommends what to test next based on current project state, recent failures, and untested areas\n\nExpand the AI Suggestions panel on the Test Runs tab to access these features.",
      },
    ],
  },

  // ─── 4. Notes ────────────────────────────────────────────────────────────
  {
    id: "notes",
    title: "Notes",
    icon: FileText,
    description: "A knowledge repository with rich text editing, file attachments, and task linking for documenting findings, test strategies, and team knowledge.",
    subsections: [
      {
        id: "notes-editor",
        title: "Rich Text Editor",
        content: "The notes editor provides full WYSIWYG editing powered by Tiptap:\n\n- **Formatting** — bold, italic, underline, strikethrough\n- **Font Options** — Inter, Poppins, or Roboto Mono\n- **Font Size** — adjustable size controls\n- **Text Color** — color picker for text highlighting\n- **Source View** — toggle to see and edit raw HTML\n\nNotes auto-save with a configurable debounce delay to prevent data loss.",
      },
      {
        id: "notes-attachments",
        title: "Attachments",
        content: "Attach files to any note for evidence and reference:\n\n- Upload files via the attachment panel\n- View attached files with metadata (name, size)\n- Open attachments directly from the note\n- Delete attachments when no longer needed\n\nAttachments are stored in the project's digital storage directory.",
      },
      {
        id: "notes-linking",
        title: "Task Linking",
        content: "Link notes to tasks to create bidirectional relationships:\n\n- Use the task dropdown to associate one or more tasks\n- Linked tasks appear in the note's sidebar entry\n- Navigate from a task's traceability panel to its linked notes\n- Filter the notes sidebar by linked task\n\nThis creates a knowledge graph connecting documentation to the work items they relate to.",
        tips: ["Link test strategy notes to their corresponding tasks so team members can quickly understand the testing approach."],
      },
    ],
  },

  // ─── 5. GitHub ───────────────────────────────────────────────────────────
  {
    id: "github",
    title: "GitHub Integration",
    icon: GitBranch,
    description: "Full GitHub integration for PR review, CI status tracking, commit browsing, and AI-powered test impact analysis.",
    subsections: [
      {
        id: "github-prs",
        title: "Pull Requests",
        content: "Browse and review pull requests with rich detail:\n\n- **Filter** by state: Open, Closed, or All\n- **Search** PRs by title or description\n- Each PR shows: title, branch, author, creation date, merge status (clean / dirty / blocked), draft indicator\n- **CI Check Status** — pass/fail/in-progress indicators per PR\n- **Review Status** — approvals and change-request counts\n- **Deployment Status** — most recent deployment info per branch\n\nClick a PR to open the **Detail Panel** showing full description, commits, changed files with diff stats, reviews, and comments.",
        tips: ["Connect your GitHub account via OAuth in Settings > Account & Identity."],
      },
      {
        id: "github-commits",
        title: "Commits",
        content: "Browse commits by branch:\n\n- Select a branch from the dropdown\n- View commit list with message, author, date, and SHA\n- Click a SHA to open the commit on GitHub\n- Track code changes over time for specific branches",
      },
      {
        id: "github-impact",
        title: "Test Impact Analysis",
        content: "AI-powered analysis of how PR changes affect your test suite:\n\n- Select a PR to analyze\n- The AI examines changed files and identifies:\n  - **Impacted test cases** — existing tests that should be re-run\n  - **Affected modules** — areas of the app touched by the changes\n  - **Rationale** — explanation of why each test is impacted\n  - **Suggested test cases** — additional tests to consider\n- **Build Regression Suite** — one-click creation of a regression suite from impacted cases",
        tips: ["Test impact analysis is most accurate when your test cases have clear module assignments and source issue links."],
      },
    ],
  },

  // ─── 6. Deployments ──────────────────────────────────────────────────────
  {
    id: "deployments",
    title: "Deployments",
    icon: Rocket,
    description: "Track GitHub Actions workflows, deployment status, and trigger workflow dispatches directly from QAssistant.",
    subsections: [
      {
        id: "deployments-workflows",
        title: "Workflow Runs",
        content: "Monitor your CI/CD pipeline:\n\n- View all workflow runs with status indicators (success, failure, in-progress)\n- Filter by workflow name\n- Expand any run to see individual job details and logs\n- **Polling** — enable live updates to watch runs in real-time\n- **Rerun** — re-trigger failed workflow runs\n- Job logs show step-by-step status breakdown",
      },
      {
        id: "deployments-envs",
        title: "Deployment Status",
        content: "Track deployments grouped by environment:\n\n- See the most recent deployment per environment\n- Deployment status and strategy indicators\n- Environment-level deployment history",
      },
      {
        id: "deployments-dispatch",
        title: "Workflow Dispatch",
        content: "Trigger GitHub Actions workflows manually:\n\n- View available dispatchable workflows\n- Select target branch\n- Execute the workflow directly from QAssistant\n\nThis is useful for triggering deployment pipelines, test suites, or build processes.",
      },
    ],
  },

  // ─── 7. Environments ─────────────────────────────────────────────────────
  {
    id: "environments",
    title: "Environments",
    icon: Globe,
    description: "Manage your QA environments with health monitoring, credential storage, and quick access to environment-specific URLs.",
    subsections: [
      {
        id: "environments-management",
        title: "Environment Management",
        content: "Create and configure environments for your testing needs:\n\n- **Types** — Development, Staging, Production, or Custom\n- **URLs** — Base URL, HAC URL, Backoffice URL, Storefront URL, Solr Admin URL, OCC Base Path, Health Check URL\n- **Credentials** — username and password stored securely in the OS keychain\n- **SSL** — option to ignore SSL errors for self-signed certificates\n- **Notes** — free-text description or instructions\n- **Default Environment** — set one environment as the default, shown in the titlebar selector",
        tips: ["Set your most-used environment as the default. The titlebar environment selector lets you quick-switch during testing."],
      },
      {
        id: "environments-health",
        title: "Health Monitoring",
        content: "Monitor environment availability:\n\n- **Manual Check** — trigger a health check on demand\n- **Auto Health Service** — background health checks at configurable intervals\n- **Status Indicators** — Healthy (green), Unhealthy (red), Unknown (gray)\n- **Latency** — response time in milliseconds\n- **Last Checked** — timestamp of most recent check\n\nHealth checks use the configured Health Check URL and report HTTP status and response time.",
      },
    ],
  },

  // ─── 8. Exploratory Testing ──────────────────────────────────────────────
  {
    id: "exploratory",
    title: "Exploratory Testing",
    icon: Compass,
    description: "Run timeboxed exploratory testing sessions with structured observation tracking and inline bug filing.",
    subsections: [
      {
        id: "exploratory-sessions",
        title: "Session Management",
        content: "Create focused exploratory testing sessions:\n\n- **Charter** — define the scope and goal of your exploration\n- **Timebox** — set a duration in minutes\n- **Tester** — assign the session to a team member\n- **Session Timer** — tracks elapsed vs total time\n- Mark sessions as complete when finished\n- Delete sessions when no longer needed",
      },
      {
        id: "exploratory-observations",
        title: "Observations & Findings",
        content: "Track what you discover during exploration:\n\n- **Observation** — neutral finding worth noting\n- **Finding** — something interesting or unexpected\n- **Bug** — a defect that needs fixing (with optional severity)\n- **Question** — something to investigate further\n\nEach observation is timestamped and displayed in a chronological timeline with type-specific icons and color coding.",
      },
      {
        id: "exploratory-bugs",
        title: "Inline Bug Filing",
        content: "When you find a bug during exploratory testing:\n\n1. Add an observation with type **Bug**\n2. Set the severity level\n3. Click to create a task directly from the observation\n4. The new task is pre-populated with the bug description and severity\n\nThis seamless workflow ensures bugs are captured immediately without breaking your testing flow.",
      },
    ],
  },

  // ─── 9. Code Reviews ────────────────────────────────────────────────────
  {
    id: "code-reviews",
    title: "Code Reviews",
    icon: Code,
    description: "A centralized PR review queue for developers, with filtering, search, and detail viewing.",
    subsections: [
      {
        id: "code-reviews-queue",
        title: "Review Queue",
        content: "View all PRs that need your review:\n\n- PRs assigned to you are listed with:\n  - Title and repository\n  - Author info with avatar\n  - Time since creation\n  - Status badges: **Draft**, **Ready** (mergeable), **Blocked** (conflicts)\n  - Change metrics: additions, deletions, files changed\n- Sort and filter the queue\n- Search by PR title or repository name",
      },
      {
        id: "code-reviews-detail",
        title: "PR Detail Panel",
        content: "Click any PR to open a side panel with:\n\n- Full PR description with expand/collapse\n- Complete list of commits\n- Files changed with addition/deletion counts\n- Review status and reviewer details\n- Comments and conversation thread\n- Quick link to open on GitHub",
        tips: ["This page is only visible to users with the Developer role. Switch roles in Settings > Account & Identity."],
      },
    ],
  },

  // ─── 10. API Page ────────────────────────────────────────────────────────
  {
    id: "api",
    title: "API Testing",
    icon: ServerCog,
    description: "A built-in REST API request builder and testing tool with templates and environment variable support.",
    subsections: [
      {
        id: "api-requests",
        title: "Request Builder",
        content: "Create and manage API requests:\n\n- **Methods** — GET, POST, PUT, PATCH, DELETE\n- **URL** — with environment variable substitution\n- **Headers** — JSON editor for custom headers\n- **Body** — JSON or form data editor\n- **Categories** — organize requests into groups\n\nSearch and filter your request library by name or URL.",
      },
      {
        id: "api-execution",
        title: "Sending Requests",
        content: "Execute requests and inspect responses:\n\n- Click **Send** to execute the request\n- View the response body and headers in separate tabs\n- See the HTTP status code and response time (ms)\n- Status icon indicates success (green) or error (red)\n\nResponses are displayed in a formatted JSON viewer.",
      },
      {
        id: "api-templates",
        title: "API Templates",
        content: "Pre-built request templates for common APIs:\n\n- **OCC API Templates** — SAP Commerce OCC endpoints (products, carts, orders)\n- **HAC Templates** — SAP Hybris Administration Console endpoints\n\nSelect a template to auto-populate the request fields, then customize as needed.",
        tips: ["Templates use environment variables like `{{baseUrl}}` that resolve to the active environment's configuration."],
      },
    ],
  },

  // ─── 11. SAP Commerce ───────────────────────────────────────────────────
  {
    id: "sap",
    title: "SAP Commerce",
    icon: Database,
    description: "Deep integration with SAP Commerce Cloud (Hybris), including HAC access, FlexSearch, ImpEx, catalog management, and CCv2 deployments.",
    subsections: [
      {
        id: "sap-hac",
        title: "HAC Connection",
        content: "Connect to the Hybris Administration Console:\n\n- Enter the HAC URL from your environment configuration\n- Authenticate with your HAC credentials\n- Once connected, all HAC tabs become available\n\nThe connection persists within the session. Re-authenticate if the session expires.",
        tips: ["Enable the SAP Commerce Context toggle in Settings > General to show SAP-specific features throughout the app."],
      },
      {
        id: "sap-flexsearch",
        title: "FlexSearch",
        content: "Execute FlexSearch (HyperSQL) queries against the Hybris database:\n\n- Write custom queries or use pre-defined templates:\n  - **Products** — query product catalog\n  - **Catalogs** — list catalog versions\n  - **Locked Users** — find locked accounts\n  - **Promotions** — query active promotions\n- Set max results limit\n- Results displayed in a sortable grid\n- **AI-powered** — describe what you want in natural language and the AI generates the FlexSearch query",
      },
      {
        id: "sap-impex",
        title: "ImpEx",
        content: "Import and export data using ImpEx scripts:\n\n- Write custom ImpEx or use snippets:\n  - **Product Insert** — add new products\n  - **Customer Insert** — add new customers\n  - **Product Removal** — remove products\n  - **Stock Level Insert** — update stock levels\n- Toggle code mode for syntax highlighting\n- Execute scripts directly against the connected HAC instance",
      },
      {
        id: "sap-catalog",
        title: "Catalog Management",
        content: "Manage SAP catalog versions:\n\n- List all catalog versions in the system\n- Lookup specific catalog IDs\n- **Sync Diff Analysis** — compare staged vs online catalog versions\n- Identify missing items between catalog versions\n\nThis helps ensure catalog synchronization is complete before releases.",
      },
      {
        id: "sap-cronjobs",
        title: "Cron Jobs",
        content: "Monitor and manage HAC cron jobs:\n\n- List all active and inactive cron jobs\n- View job status and schedule\n- Trigger job execution manually\n- Monitor job completion",
      },
      {
        id: "sap-ccv2",
        title: "Commerce Cloud v2 (CCv2)",
        content: "Manage your SAP Commerce Cloud v2 environments:\n\n- View all CCv2 environments\n- Track deployment history and status\n- Monitor build status\n- See deployment strategy indicators\n\nConfigure CCv2 access in Settings > SAP Commerce Cloud v2 with your subscription code and API token.",
      },
    ],
  },

  // ─── 12. Report Builder ──────────────────────────────────────────────────
  {
    id: "reports",
    title: "Report Builder",
    icon: BarChart3,
    description: "Create custom test reports from configurable templates with multiple export formats.",
    subsections: [
      {
        id: "reports-templates",
        title: "Report Templates",
        content: "Manage report templates:\n\n- **Default Templates** — Executive Summary, Full Test Report, Risk Assessment\n- **Custom Templates** — create your own report layouts\n- Edit, duplicate, or delete templates\n- Templates define which sections appear and in what order",
      },
      {
        id: "reports-sections",
        title: "Report Sections",
        content: "Available report sections:\n\n- **Overview Stats** — high-level metrics summary\n- **Status Breakdown** — detailed status distribution\n- **Health Score** — project health indicator\n- **Impact Assessment** — risk and impact analysis\n- **Test Plan Details** — per-plan test case listings\n- **Execution History** — recent test run results\n- **Session Summary** — exploratory testing session summaries\n- **Open Tasks** — unresolved task listing\n- **Flaky Tests** — tests with inconsistent results\n- **Coverage Matrix** — task-to-test coverage view\n\nDrag sections to reorder, enable or disable individual sections.",
      },
      {
        id: "reports-export",
        title: "Export Formats",
        content: "Generate reports in your preferred format:\n\n- **HTML** — web-viewable report\n- **PDF** — print-ready document\n- **Markdown** — for documentation systems\n- **CSV** — for spreadsheet analysis\n\nSelect a template, preview the report, and export with one click.",
      },
    ],
  },

  // ─── 13. Activity Feed ───────────────────────────────────────────────────
  {
    id: "activity",
    title: "Activity Feed",
    icon: Activity,
    description: "A chronological view of all collaboration events between QA and Development teams.",
    subsections: [
      {
        id: "activity-events",
        title: "Event Types",
        content: "The activity feed tracks these event types:\n\n- **Handoff Created / Sent** — new bug handoff initiated\n- **Handoff Acknowledged** — developer confirmed receipt\n- **Fix Started** — developer began work on the fix\n- **PR Linked** — pull request associated with a task\n- **Ready for QA** — fix submitted for QA verification\n- **Retest Started** — QA began retesting\n- **Verification Passed / Failed** — retest outcome\n- **Evidence Added** — screenshot, log, or file attached\n- **Note Linked** — documentation associated with a task\n- **Execution Linked** — test execution associated with a task\n\nEach event shows an icon, title, details, timestamp, and link to the related task.",
      },
      {
        id: "activity-filtering",
        title: "Filtering",
        content: "Narrow down the activity feed:\n\n- **Role Filter** — view All events, QA-only events, or Dev-only events\n- **Event Type Filter** — select specific event types to display\n- **Search** — filter by title or details text\n- Events are sorted newest-first by default",
      },
    ],
  },

  // ─── 14. Checklists ─────────────────────────────────────────────────────
  {
    id: "checklists",
    title: "Checklists",
    icon: ClipboardCheck,
    description: "Create and manage checklists for releases, deployments, testing, and other operational processes.",
    subsections: [
      {
        id: "checklists-management",
        title: "Checklist Management",
        content: "Organize your operational checklists:\n\n- **Create** checklists with a title and category\n- **Categories** — Release, Deployment, Testing, or Other\n- **Add Items** — define checklist items with descriptions\n- **Batch Edit** — modify multiple items at once\n- **Delete** checklists when no longer needed",
      },
      {
        id: "checklists-progress",
        title: "Execution & Progress",
        content: "Track checklist completion:\n\n- Check/uncheck individual items as you complete them\n- **Progress Bar** — visual completion percentage\n- Edit item text inline\n- Reorder items as needed\n\nUse checklists as pre-release gates to ensure all steps are completed before deploying.",
        tips: ["Create a release checklist template and duplicate it for each release to maintain consistency."],
      },
    ],
  },

  // ─── 15. Runbooks ────────────────────────────────────────────────────────
  {
    id: "runbooks",
    title: "Runbooks",
    icon: ListChecks,
    description: "Operational runbooks for deployment procedures, maintenance tasks, and testing workflows with step-by-step execution tracking.",
    subsections: [
      {
        id: "runbooks-management",
        title: "Runbook Management",
        content: "Create detailed operational procedures:\n\n- **Categories** — Deployment, Maintenance, Testing, Other\n- **Ordered Steps** — each step has a description and status\n- **Step Statuses** — Pending, In-Progress, Done, Failed, Skipped\n- Reorder steps with drag-and-drop\n- Add or remove steps as procedures evolve",
      },
      {
        id: "runbooks-execution",
        title: "Execution Tracking",
        content: "Track runbook execution in real-time:\n\n- Mark steps as complete as you progress\n- Record failures when steps don't succeed\n- Skip steps that aren't applicable\n- Timestamps track when each step was completed\n\nRunbooks provide a repeatable, auditable process for complex operations.",
        tips: ["Use runbooks for deployment procedures to ensure no steps are missed during high-pressure releases."],
      },
    ],
  },

  // ─── 16. Test Data ──────────────────────────────────────────────────────
  {
    id: "test-data",
    title: "Test Data",
    icon: Database,
    description: "Centralized test data management for organizing credentials, test users, product data, and other testing resources.",
    subsections: [
      {
        id: "test-data-groups",
        title: "Data Groups",
        content: "Organize test data into logical groups:\n\n- Create groups by type (Users, Credentials, Products, Addresses, etc.)\n- Each group contains multiple data entries\n- Groups can be associated with specific environments\n- Search and filter to quickly find data",
      },
      {
        id: "test-data-entries",
        title: "Data Entries",
        content: "Each entry stores structured test data:\n\n- **Key-Value Pairs** — flexible data storage (e.g., username: \"testuser1\")\n- **Description** — notes about the data and its purpose\n- **Tags** — searchable labels for quick lookup\n- **Environment** — which environment this data applies to\n\nUse test data entries to maintain a central source of truth for test credentials, API keys, and sample data.",
        tips: ["Keep environment-specific data (like URLs and credentials) in both Environments and Test Data for quick reference during test execution."],
      },
    ],
  },

  // ─── 17. Files ──────────────────────────────────────────────────────────
  {
    id: "files",
    title: "Files",
    icon: Folder,
    description: "A centralized file repository for evidence, attachments, screenshots, and other artifacts.",
    subsections: [
      {
        id: "files-management",
        title: "File Management",
        content: "Upload and organize project files:\n\n- **Drag-and-drop** upload for quick file addition\n- **Browse** to select files from your system\n- **Bulk Upload** — add multiple files at once\n- View file metadata: filename, size, MIME type, upload date\n- **Preview** supported file types directly in the app\n- **Download / Open** files with system default applications\n- **Delete** files when no longer needed",
      },
      {
        id: "files-linking",
        title: "File Linking",
        content: "Connect files to other artifacts:\n\n- Link files to **tasks** as bug evidence\n- Link files to **test cases** as test artifacts\n- Link files to **notes** as supporting documentation\n- Link files to **handoff packets** as reproduction evidence\n- **Unlink** files to remove associations\n\nLinked files appear in the traceability panel of the associated artifact.",
        tips: ["Attach screenshots and logs to handoff packets so developers have all the evidence they need to reproduce bugs."],
      },
    ],
  },

  // ─── 18. Settings ───────────────────────────────────────────────────────
  {
    id: "settings",
    title: "Settings",
    icon: Settings,
    description: "Configure your QAssistant instance including integrations, appearance, credentials, and project sharing.",
    subsections: [
      {
        id: "settings-account",
        title: "Account & Identity",
        content: "Manage your user profile:\n\n- **Role** — switch between QA and Developer roles to show/hide role-specific features\n- **Connected Identities** — view OAuth connections for GitHub and Linear\n- **Connect / Disconnect** — manage OAuth authentication flows\n\nYour role affects which navigation items and features are visible.",
      },
      {
        id: "settings-appearance",
        title: "Appearance",
        content: "Customize the look of QAssistant:\n\n- **Theme Toggle** — switch between Dark and Light themes\n\nThe dark theme uses a deep background with purple (#A78BFA) accents. The light theme provides a clean, bright interface.",
      },
      {
        id: "settings-general",
        title: "General",
        content: "General application settings:\n\n- **SAP Commerce Context** — enable/disable SAP-specific features throughout the app\n- **Minimize to Tray** — keep QAssistant running in the system tray when closed",
      },
      {
        id: "settings-automation",
        title: "Automation API",
        content: "Configure the built-in REST API server:\n\n- **Enable/Disable** the API server\n- **Port** — configure which port the API runs on\n- **API Key** — generate, regenerate, or copy your bearer token\n- **Endpoints** — view available REST endpoints\n\nThe Automation API allows external tools (CI/CD pipelines, scripts) to interact with QAssistant programmatically.",
      },
      {
        id: "settings-linear",
        title: "Linear",
        content: "Connect to Linear for issue tracking:\n\n- **Add Connection** — configure API key or OAuth token\n- **Team ID** — specify which Linear team to sync\n- **Test Connection** — verify credentials work\n- Multiple connections supported per project",
      },
      {
        id: "settings-jira",
        title: "Atlassian Jira",
        content: "Connect to Jira for issue tracking:\n\n- **Domain** — your Jira instance URL\n- **Email** — your Jira account email\n- **API Token** — Jira API token for authentication\n- **Project Key** — which Jira project to sync\n- **Test Connection** — verify the configuration",
      },
      {
        id: "settings-ai",
        title: "Google AI Studio",
        content: "Configure the Gemini AI integration:\n\n- **API Key** — enter your Google AI Studio API key\n- **Model Selection** — choose from available Gemini models or enter a custom model ID\n- **Model Discovery** — fetch the list of available models from the API\n\nThe AI powers test case generation, issue analysis, standup summaries, and more.",
      },
      {
        id: "settings-ccv2",
        title: "SAP Commerce Cloud v2",
        content: "Connect to SAP CCv2:\n\n- **Subscription Code** — your CCv2 subscription identifier\n- **API Token** — authentication token for the CCv2 API\n- **Test Connection** — verify access\n- **Disconnect** — remove the configuration",
      },
      {
        id: "settings-sharing",
        title: "Project Sharing",
        content: "Import and export project data:\n\n- **Export** — save the current project as a JSON file\n- **Import** — load a project from a JSON file\n\nNote: Credentials (API keys, passwords) are NOT included in exports for security. You will need to reconfigure integrations after importing.",
      },
      {
        id: "settings-webhooks",
        title: "Webhooks & Notifications",
        content: "Set up webhook notifications:\n\n- **Webhook Types** — Slack, Microsoft Teams, or Generic (custom URL)\n- **Event Triggers** — choose which events send notifications\n- **Enable/Disable** individual webhooks\n- **Test** webhooks to verify delivery\n\nWebhooks notify your team when important events occur (new bugs, test failures, handoff state changes).",
      },
      {
        id: "settings-diagnostics",
        title: "Diagnostics",
        content: "System information and maintenance:\n\n- **System Info** — app version, platform, architecture, Node/Electron versions\n- **Data Path** — where project files are stored on disk\n- **Credentials** — manage stored credentials in the OS keychain\n- **Orphan Scanner** — find and clean up attachment files not linked to any artifact\n- **Purge All Data** — nuclear option to wipe all data (use with extreme caution)",
      },
    ],
  },

  // ─── 19. Automation API ─────────────────────────────────────────────────
  {
    id: "automation-api",
    title: "Automation API",
    icon: Zap,
    description: "QAssistant includes a built-in REST API server for programmatic access from CI/CD pipelines, scripts, and external tools.",
    subsections: [
      {
        id: "automation-overview",
        title: "Overview",
        content: "The Automation API is an Express-based HTTP server running inside the Electron app. When enabled (Settings > Automation API), it exposes REST endpoints for:\n\n- Reading and managing projects\n- Submitting test results\n- Querying test cases\n- Creating and managing handoffs\n- Checking release readiness\n- Establishing traceability links",
      },
      {
        id: "automation-auth",
        title: "Authentication",
        content: "All API requests require a bearer token:\n\n- Generate an API key in Settings > Automation API\n- Include the key in the `Authorization` header:\n  `Authorization: Bearer YOUR_API_KEY`\n- Regenerate the key if compromised\n- The OAuth callback endpoint is public (no auth required)",
      },
      {
        id: "automation-endpoints",
        title: "Key Endpoints",
        content: "Available REST endpoints:\n\n- `GET /api/projects` — list all projects\n- `GET /api/testcases` — list test cases for a project\n- `POST /api/results` — submit a single test result\n- `POST /api/results/batch` — submit multiple test results\n- `GET /api/release-readiness` — evaluate quality gates\n- `POST /api/traceability` — link a task to a test case\n- `GET /api/handoffs` — list handoff packets\n- `POST /api/handoffs/:id/acknowledge` — acknowledge a handoff\n- `POST /api/handoffs/:id/verify` — verify a fix\n\nAll endpoints return JSON responses.",
        tips: ["Use the batch results endpoint in your CI pipeline to submit test results automatically after each test run."],
      },
    ],
  },

  // ─── 20. AI Features ────────────────────────────────────────────────────
  {
    id: "ai-features",
    title: "AI Features",
    icon: Cpu,
    description: "QAssistant integrates with Google Gemini to provide AI-powered capabilities across the application.",
    subsections: [
      {
        id: "ai-overview",
        title: "Setup & Configuration",
        content: "To use AI features:\n\n1. Get an API key from **Google AI Studio** (aistudio.google.com)\n2. Open Settings > Google AI Studio\n3. Paste your API key\n4. Select a model (recommended: Gemini 2.5 Flash or later)\n5. Click **Fetch Models** to see available options\n\nThe AI automatically falls back between model versions for reliability. Token limits are optimized per feature to control costs.",
      },
      {
        id: "ai-capabilities",
        title: "AI Capabilities",
        content: "AI is integrated throughout the app:\n\n- **Test Case Generation** (Tests) — generate comprehensive test cases from task descriptions or free text\n- **Issue Analysis** (Tasks) — deep analysis of bugs with root cause assessment\n- **Criticality Assessment** (Tests) — determine which tests matter most\n- **Test Run Suggestions** (Tests) — AI recommends what to test next\n- **Smoke Test Subset** (Tests) — minimal test set for quick validation\n- **Test Impact Analysis** (GitHub) — identify tests affected by PR changes\n- **Standup Summary** (Dashboard) — auto-generate daily standup reports\n- **Duplicate Bug Detection** (Tasks) — find semantically similar bugs\n- **FlexSearch Generation** (SAP) — natural language to SQL query conversion\n- **AI Accuracy Evaluation** (Tests) — evaluate chatbot response quality\n- **AI Copilot** (Global) — conversational chat assistant available from the titlebar",
      },
      {
        id: "ai-copilot",
        title: "AI Copilot",
        content: "The AI Copilot is a floating chat interface accessible from the sparkle icon in the titlebar:\n\n- Ask questions about your project\n- Get help with testing strategies\n- Request analysis of specific tasks\n- Multi-turn conversation support\n- Context-aware responses using your project data\n\nThe copilot maintains conversation history within the session.",
        tips: ["The AI Copilot has access to your project context (tasks, tests, environments) so you can ask specific questions about your testing progress."],
      },
    ],
  },

  // ─── 21. Keyboard Shortcuts & Navigation ─────────────────────────────────
  {
    id: "shortcuts",
    title: "Keyboard Shortcuts & Navigation",
    icon: Keyboard,
    description: "Navigate QAssistant efficiently with keyboard shortcuts, the command palette, and sidebar navigation.",
    subsections: [
      {
        id: "shortcuts-palette",
        title: "Command Palette",
        content: "Open the Command Palette with `Ctrl+K` (or `Cmd+K` on macOS):\n\n- Quick-search for any page or action\n- Navigate to any section instantly\n- Execute common operations without leaving the keyboard\n\nThe command palette searches across page names and available actions.",
      },
      {
        id: "shortcuts-global",
        title: "Global Shortcuts",
        content: "Keyboard shortcuts available anywhere in the app:\n\n- `Ctrl+K` / `Cmd+K` — Open Command Palette\n- `Ctrl+N` / `Cmd+N` — Quick Add Task\n- `Ctrl+,` / `Cmd+,` — Open Settings\n- `F1` — Open Documentation\n\nThese shortcuts work regardless of which page you are on.",
      },
      {
        id: "shortcuts-navigation",
        title: "Sidebar Navigation",
        content: "The sidebar provides structured navigation:\n\n- **Projects Sidebar** (left) — switch between projects, create new ones, load demo project\n- **Tools Sidebar** (middle) — navigate between pages, grouped by category\n  - Dashboard (always visible)\n  - Organization: Notes, Files\n  - QA sections: Tasks, Tests, Code Reviews, etc.\n  - Dev Tools: GitHub, Environments, API, etc.\n- **Collapse** the tools sidebar with the chevron button for more content space\n- **Search** the navigation items to quickly find pages\n\nNavigation items are filtered by your active role (QA vs Developer).",
      },
      {
        id: "shortcuts-list-nav",
        title: "List Navigation",
        content: "In list views (tasks, notes, PRs), use Vim-style keyboard navigation:\n\n- `j` — move down in the list\n- `k` — move up in the list\n- `Enter` — select the highlighted item\n- `o` — open the highlighted item\n- `Escape` — exit the list focus\n\nThis navigation is disabled when focused on text inputs to avoid conflicts.",
      },
    ],
  },
]
